set dotenv-load
set positional-arguments
set shell := ["bash", "-uc"]

run *args:
    go run ./cmd/api {{args}}

confirm:
    @echo -n "Are you sure? [y/N] " && read ans && [ ${ans:-N} == y ]

watch *args:
    watchexec -r -e go,html -- just run {{args}}

up: confirm
    migrate -path=./migrations -database=$DB_DSN up

migrate name:
    migrate create -seq -ext=.sql -dir=./migrations {{name}}

