set dotenv-load
set positional-arguments
set shell := ["bash", "-uc"]

run *args:
    go run ./cmd/api {{args}}

watch *args:
    watchexec -r -e go,html -- just run {{args}}

[confirm("Run migrations [y/N]")]
up: 
    migrate -path=./migrations -database=$DATABASE_URL up

migrate name:
    migrate create -seq -ext=.sql -dir=./migrations {{name}}

